# Generated by Django 3.0.7 on 2020-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('n', 'New'), ('r', 'Sales read'), ('f', 'Sales follow'), ('d', 'Sales done'), ('c', 'Contributor request'), ('e', 'Contributor in exchange'), ('a', 'Contributor done'), ('or', 'Other read'), ('of', 'Other follow'), ('od', 'Other done')], default='n', max_length=2)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
