# Generated by Django 3.0.6 on 2020-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200524_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contributor',
            field=models.BooleanField(default=False),
        ),
    ]
