# Generated by Django 3.0.7 on 2020-07-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_main', models.ImageField(blank=True, upload_to='original_images')),
                ('image_two', models.ImageField(blank=True, upload_to='original_images')),
                ('image_three', models.ImageField(blank=True, upload_to='original_images')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('h', 'Highlight'), ('a', 'Active'), ('i', 'Inactive')], default='a', max_length=1)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Original')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('scale', models.CharField(default='', max_length=60)),
                ('place', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('image_main', models.ImageField(upload_to='product_images')),
                ('image_sec', models.ImageField(blank=True, upload_to='product_images')),
                ('status', models.CharField(choices=[('p', 'Promotion'), ('s', 'Soldout'), ('o', 'Out of stock'), ('n', 'Not on sales'), ('y', 'On sales')], default='y', max_length=1)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('original_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.Original')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'highlight'), name='up_vote'),
        ),
    ]
