# Generated by Django 3.0.7 on 2020-07-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200727_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scale',
        ),
    ]
