# Generated by Django 3.0.6 on 2020-05-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promo_price',
            new_name='old_price',
        ),
    ]
