# Generated by Django 3.0.7 on 2020-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original',
            name='make',
        ),
        migrations.RemoveField(
            model_name='product',
            name='make',
        ),
        migrations.AddField(
            model_name='original',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
