# Generated by Django 3.0.7 on 2020-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='model',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
