# Generated by Django 3.0.6 on 2020-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200517_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='original',
            name='votes',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
