# Generated by Django 3.0.6 on 2020-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200517_1751'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='up_vote',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'highlight'), name='Voted'),
        ),
    ]
