# Generated by Django 3.0.6 on 2020-05-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200518_1204'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Voted',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'highlight'), name='up_vote'),
        ),
    ]
