# Generated by Django 3.0.6 on 2020-05-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200518_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Original'),
        ),
    ]
