# Generated by Django 3.0.6 on 2020-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200518_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='date',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='original',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='original',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='original_images'),
        ),
        migrations.AlterField(
            model_name='original',
            name='make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='original',
            name='model',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
