# Generated by Django 3.0.6 on 2020-06-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200519_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.Original'),
        ),
    ]
