# Generated by Django 3.0.7 on 2020-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200617_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='original',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
