# Generated by Django 3.0.7 on 2020-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200724_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
